# Generated by Django 4.1.7 on 2023-02-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app10', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='service_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='service/')),
            ],
        ),
    ]
