# Generated by Django 4.1.7 on 2023-02-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app10', '0003_project_tb_alter_service_tb_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galleryimg/')),
            ],
        ),
    ]
