# Generated by Django 4.1.7 on 2023-02-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app10', '0004_gallery_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
