# Generated by Django 4.1.7 on 2023-03-08 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app10', '0005_contact_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='getin_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app10.service_tb')),
            ],
        ),
    ]
